In [1]:
import torch
import numpy as np

In [ ]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)

print(data_tensor)       # Shows tensor content
print(type(data_tensor)) # Shows torch.Tensor type
print(data_tensor, type(data_tensor))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [ ]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))

np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4],
        [5, 6]]) <class 'torch.Tensor'>


In [7]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [8]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [9]:
torch.rand(3, 3, 3)

tensor([[[0.4375, 0.8904, 0.5829],
         [0.3746, 0.9032, 0.6083],
         [0.5048, 0.1138, 0.6633]],

        [[0.4335, 0.8423, 0.9592],
         [0.6477, 0.3239, 0.6598],
         [0.4042, 0.6901, 0.7048]],

        [[0.4012, 0.8378, 0.6678],
         [0.1412, 0.7546, 0.2947],
         [0.9706, 0.7890, 0.0274]]])

In [11]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)

print(zero_tensor)
print(ones_like_zeros)

print(zero_tensor.shape, ones_like_zeros.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3, 3]) torch.Size([3, 3])


In [8]:
zero_tensor[0]

tensor([0., 0., 0.])

In [9]:
ones_like_zeros[:, 0]

tensor([1., 1., 1.])

In [ ]:
x = ones_like_zeros.detach()
print(x)

In [ ]:
x[:, 0] * 5

In [ ]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

In [ ]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)