In [1]:
import torch
import numpy as np

In [ ]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)

print(data_tensor)       # Shows tensor content
print(type(data_tensor)) # Shows torch.Tensor type
print(data_tensor, type(data_tensor))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [ ]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))

np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4],
        [5, 6]]) <class 'torch.Tensor'>


In [7]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [8]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [9]:
torch.rand(3, 3, 3)

tensor([[[0.4375, 0.8904, 0.5829],
         [0.3746, 0.9032, 0.6083],
         [0.5048, 0.1138, 0.6633]],

        [[0.4335, 0.8423, 0.9592],
         [0.6477, 0.3239, 0.6598],
         [0.4042, 0.6901, 0.7048]],

        [[0.4012, 0.8378, 0.6678],
         [0.1412, 0.7546, 0.2947],
         [0.9706, 0.7890, 0.0274]]])

In [11]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)

print(zero_tensor)
print(ones_like_zeros)

print(zero_tensor.shape, ones_like_zeros.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3, 3]) torch.Size([3, 3])


In [8]:
zero_tensor[0]

tensor([0., 0., 0.])

In [ ]:
# [:, 0] is a NumPy-style slice where ":" means "all rows" and "0 means "first column" (PyTorch uses 0-based indexing)

ones_like_zeros[:, 0]

tensor([1., 1., 1.])

`.detach()` creates a non-gradient copy of a tensor, breaking its connection to the computation graph. Here's what it does:

Key Effects:
1. Removes Gradient Tracking:
   • Original tensor: `requires_grad=True` (if part of a neural network)
   • After `.detach()`: `requires_grad=False`

2. Shares Storage (Memory Efficient):
   ```python
   y = x.detach()  # y shares data with x but won't track gradients
   ```

3. Common Use Cases:
   • Freezing weights during training
   • Extracting intermediate values without affecting backpropagation
   • Converting tensors to NumPy (requires detaching first)

Example:
```python
# Original tensor with gradients
w = torch.tensor([1., 2], requires_grad=True)
y = w * 2  # y is connected to computation graph

# Detached version
y_detached = y.detach()  # No longer connected to 'w'
```

What Happens in Your Code:
```python
x = ones_like_zeros.detach()
```

• Creates a new tensor `x` with the same values as `ones_like_zeros`
• If `ones_like_zeros` was part of a gradient calculation, `x` won't be
• Useful when you need the tensor value but don't want to affect backpropagation

In [12]:
x = ones_like_zeros.detach()
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [13]:
x[:, 0] * 5

tensor([5., 5., 5.])

**Improving PyTorch Code Quality**

`torch.matmul` is PyTorch's matrix multiplication function. Here's what you need to know:

Key Features:
1. Performs proper matrix multiplication (not element-wise)
2. Handles various tensor shapes:
   • Vectors (1D), matrices (2D), and higher-dimension tensors
3. Supports broadcasting like NumPy

Common Uses:
```python
# Matrix-vector multiplication
A = torch.rand(3, 4)  # 3×4 matrix
x = torch.rand(4)     # 4-element vector
y = torch.matmul(A, x) # Result is 3-element vector

# Matrix-matrix multiplication
B = torch.rand(4, 5)
C = torch.matmul(A, B) # Result is 3×5 matrix
```

Equivalent Operations:
```python
# These do the same thing:
torch.matmul(A, B)
A @ B  # Python 3.5+ operator
```

Special Cases:
• Batched matrix multiplication (for 3D tensors)
• Broadcasting for different shaped tensors

Example with different dimensions:
```python
# 3D tensor multiplication (batch processing)
batch = torch.rand(10, 3, 4)  # 10 matrices of size 3×4
result = torch.matmul(batch, A) # Returns 10 matrices of size
```

In [15]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)

print(rand1)
print(rand2)

print(torch.matmul(rand1, rand2))

tensor([0.7546, 0.2490, 0.9951, 0.3871, 0.2140])
tensor([0.0629, 0.0435, 0.0882, 0.3661, 0.7380])
tensor(0.4457)


In [ ]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)